# Generated by Django 5.2.4 on 2025-10-15 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
