# Generated by Django 5.2.7 on 2025-10-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0002_alter_task_deadline"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompletedTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("goal_name", models.CharField(max_length=255)),
                ("task_name", models.CharField(max_length=255)),
                ("deadline", models.CharField(blank=True, max_length=100, null=True)),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
